//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorInfo
    {
        public int AID { get; set; }
        public string AuthorName { get; set; }
        public int BookID { get; set; }
        public string City { get; set; }
        [JsonIgnore]
        public virtual BookInfo BookInfo { get; set; }
    }
}
